apiVersion: v1
kind: BuildConfig
metadata:
  name: node-app-build
spec:
  runPolicy: Serial
  triggers:
    - type: ImageChange
    - type: ConfigChange
  source:
    type: Git
    git:
      uri: "https://github.com/cybercom-finland/hacking-great-3"
      ref: master
    contextDir: "t1-docker/node-app"
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: "node-app-stream:latest"
