apiVersion: v1
kind: DeploymentConfig
metadata:
  name: node-app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: node-app-containers
    spec:
      containers:
        - name: node-app
          image: "mylocal/node-app-image"
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 3
            timetoutSeconds: 1
          linevessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 3
            timetoutSeconds: 1
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - node-app
        from:
          kind: ImageStreamTag
          name: "node-app-stream:latest"
  strategy:
    type: Rolling
